/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.tjenwellens.lessenroosterchecker.gui;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.LinkedList;
import java.util.TreeSet;
import javax.swing.JCheckBox;
import javax.swing.JFrame;

/**
 *
 * @author Tjen
 */
public class CourseSelectionPanel extends javax.swing.JPanel {
    private JFrame frame;
    private Collection<JCheckBox> boxes = new LinkedList<>();

    /**
     * Creates new form CourseSelectionPanel
     */
    public CourseSelectionPanel(JFrame frame) {
        this.frame = frame;
        initComponents();
    }

    public void setOptions(Collection<String> options) {
        options = new TreeSet<>(options);
        plnCheckboxes.removeAll();
        plnCheckboxes.setLayout(new GridLayout(options.size(), 1));
        for (String courseName : options) {
            JCheckBox box = new JCheckBox(courseName);
            boxes.add(box);
            plnCheckboxes.add(box);
        }
        frame.pack();
        frame.setVisible(true);
    }

    public static CourseSelectionPanel create() {
        JFrame frame = new JFrame("Lessenrooster Checker");
        CourseSelectionPanel panel = new CourseSelectionPanel(frame);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setContentPane(panel);
        frame.pack();
        return panel;
    }

    public Collection<String> getSelection() {
        LinkedList<String> selection = new LinkedList<>();
        for (JCheckBox box : boxes) {
            if (box.isSelected()) {
                selection.add(box.getText());
            }
        }
        return selection;
    }

    public void addBntOkListener(ActionListener al) {
        btnOk.addActionListener(al);
    }

    public void hideFrame() {
        frame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnCheckboxes = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        plnCheckboxes.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout plnCheckboxesLayout = new javax.swing.GroupLayout(plnCheckboxes);
        plnCheckboxes.setLayout(plnCheckboxesLayout);
        plnCheckboxesLayout.setHorizontalGroup(
            plnCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plnCheckboxesLayout.setVerticalGroup(
            plnCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        btnOk.setText("OK");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plnCheckboxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 244, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnCheckboxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel plnCheckboxes;
    // End of variables declaration//GEN-END:variables
    //
}
