/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.tjenwellens.lessenroosterchecker.gui;

import eu.tjenwellens.lessenroosterchecker.elements.Les;
import eu.tjenwellens.lessenroosterchecker.elements.LesCreator;
import eu.tjenwellens.lessenroosterchecker.elements.TimeStamp;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.util.Collection;
import javax.swing.JFrame;

/**
 *
 * @author Tjen
 */
public class VisualLessenRooster extends javax.swing.JPanel {
    private JFrame frame;
    private int[][] lessen;

    /**
     * Creates new form VisualLessenRooster
     */
    private VisualLessenRooster(JFrame frame, int[][] lessen) {
        this.frame = frame;
        this.lessen = lessen;
        initComponents();
        this.setPreferredSize(new Dimension(500, 850));
    }

    public void setLessen(int[][] lessen) {
        this.lessen = lessen;
        invalidate();
        validate();
    }

    public static VisualLessenRooster create(int[][] rooster) {
        JFrame frame = new JFrame("Visual");
        VisualLessenRooster panel = new VisualLessenRooster(frame, rooster);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(panel);
        frame.pack();
        frame.setVisible(true);
        return panel;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Dimension size = new Dimension(50, 20);
        Point offset = new Point(100, size.height + 10);
        for (int dag = 0; dag < lessen.length; dag++) {
            for (int kwart = 0; kwart < lessen[dag].length; kwart++) {
                Color c;
                switch (lessen[dag][kwart]) {
                    case 0:
                        c = Color.white;
                        break;
                    case 1:
                        c = Color.green;
                        break;
                    case 2:
                        c = Color.orange;
                        break;
                    case 3:
                        c = Color.red;
                        break;
                    default:
                        c = Color.black;
                }
                g.setColor(c);
                g.fillRect(offset.x + size.width * dag, offset.y + size.height * kwart, offset.x + size.width * (dag + 1), offset.y + size.height * (kwart + 1));
            }
        }
        g.setColor(Color.black);
        for (int dag = 0; dag <= lessen.length; dag++) {
            g.drawLine(offset.x + size.width * dag, offset.y, offset.x + size.width * dag, offset.y + size.height * lessen[0].length);
        }
        for (int kwart = 0; kwart <= lessen[0].length; kwart++) {
            g.drawLine(offset.x, offset.y + size.height * kwart, offset.x + size.width * lessen.length, offset.y + size.height * kwart);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
